version: "3.2.6"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

services: 
  website:
    image: my_portfolio_website:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    depends_on:
      - db_migrate
    ports:
      - "8000:8000"

  db_migrate:
    image: my_portfolio_website:latest
    command: python manage.py migrate
    volumes: *service-volumes
